server:
  servlet:
    context-path: /
spring:
  application:
    name: Notification
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: false
      pool-name: notification-db-pool
    url: jdbc:mysql://mysql.test.svc.cluster.local:3306/zdx_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wQylNshf9y
  jackson:
    default-property-inclusion: NON_NULL
    serialization.write_dates_as_timestamps: true
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: com.zdx.notification.util.RealNamingStrategyImpl
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
  rabbitmq:
    host: rabbitmq.test.svc.cluster.local
    port: 5672
    username: MQ_USER
    password: i4U1Wolsp2
#    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: auto
  redis:
    database: 3
    host: redis-master.test.svc.cluster.local
    password: UFl3MpJaPz
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
app:
  chain:
    network: 1
info:
  head: head
  body: body
ntf:
  sms:
    ali:
      domain: sms-intl.ap-southeast-1.aliyuncs.com
      region-id: ap-southeast-1
      sign-name: zdx验证码
      version: 2018-05-01
      key: LTAI4FqFHVpaV2QMb3hWVGbo
      secret: J5aaRFj4YB2DflBQBms8XsqW6eGUnH
    yunpian:
      apikey: e8f53bf28b273e1614a19da449b20834
  email:
    ali:
      smtp: smtpdm.aliyun.com
      from: zdx-test@sre.shusj.com
      from-name: zdx
      use-ssl: true
      port: 465
      password: TWmAI5L4Bd